### ISSUE TITLE
npm run dev Doesn't work on Windows

### ISSUE THREAD

**Issue by lukeramsden** [callmecavs/bandito#2]
Running `npm run dev` throws an error pertaining to the NODE_ENV variable.
The error is as follows: 

````
> set NODE_ENV=development && webpack-dev-server --hot --inline

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1257:14)
    at listen (net.js:1293:10)
    at net.js:1403:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "c:\\program files\\nodejs\\node.exe" "c:\\Users\\*REDACTED*\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE
npm ERR! @0.0.1 dev:  set NODE_ENV=development && webpack-dev-server --hot --inline
npm ERR! Exit status 1

````

**Comment by callmecavs** [comment]
You already had something running on port 3000, as described by the error message. Kill all node related processes, and try again. Please let me know if that resolves it.

**Comment by callmecavs** [comment]
Optionally, change the webpack config to run the dev server on a different port.

**Comment by lukeramsden** [comment]
@callmecavs oh whoops 😂 Yeah that was it, sorry, I'm really new to Node and webpack. Thanks!

**Comment by callmecavs** [comment]
@lukeramsden no worries at all - node isn't known for the best error messages ;) I only recognized this one because I've run into it before myself.
